---
title: "Module 5: Exploratory data analysis with spatial data"
format: html
---

::: {.callout-note}
## Relevant Learning Standards

14. Load, manipulate, and perform mathematical operations on raster data, including multi-layer operations and unit conversions.
15. Convert between spatial data types (e.g., non-spatial to spatial, vector/raster) to enable different forms of spatial analysis.
16. Apply zonal statistics to extract summary values from raster data for polygon and point vector datasets, and integrate those results with attribute data.
17. Calculate and interpret descriptive spatial statistics such as mean center, and connect the geographic distribution of observations to patterns in the data.
:::

## Course materials { .module-section }

# Scripts
* [S11: Point pattern analysis in R](https://github.com/communitymaplab/geog4300_datascience/raw/refs/heads/main/.scripts/geog4300_S11%20Point%20pattern%20analysis%20in%20R.qmd){target="_blank"}
* [S12: Spatial functions and geocoding](https://github.com/communitymaplab/geog4300_datascience/raw/refs/heads/main/.scripts/geog4300_S12%20spatial%20functions%20and%20geocoding.qmd){target="_blank"}
* [S14: Raster data in R](https://github.com/communitymaplab/geog4300_datascience/raw/refs/heads/main/.scripts/geog4300_S14%20raster%20data%20in%20R.qmd){target="_blank"}

# Slides for class
* [L07: Point pattern analysis](https://github.com/communitymaplab/geog4300_datascience/raw/refs/heads/main/in_class_slides/geog4300_L07%20Point%20pattern%20analysis%20and%20MAUP.pptx){target="_blank"}

## Additional Resources {.module-section}

# Readings
* [Chapters 4, 5, 6, and 8 of *Geocomputation with R*](https://r.geocompx.org/spatial-operations){target="_blank"} 
* [Chapters 3-5 of *R-GIS for Ecology*](https://aterui.github.io/rgis-for-ecology/raster-data-terra-basics.html){target="_blank"}. These chapters give an overview of `sf`, `terra`, and methods of going between vector and raster data.
* [Chapter 2 of *Spatial Statistics with R*](https://edzer.github.io/sswr/day2.html){target="_blank"}, which gives a good overview of the universe of spatial packages for R and sf's formatting. It uses `spatstat` for point-pattern analysis, which has its own data formatting.


# Videos
* [ArcGIS Pro: Calculating Zonal Statistics](https://www.youtube.com/watch?v=PU0z5q23_Ss){target="_blank"} by Tessellations Incorporated. Uses ESRI tools but provides an introduction to this method of analysis
* [Introduction to Spatial Statistics](https://www.youtube.com/watch?v=VmWS_gSrCbk&t){target="_blank"} by GIScience. Includes a good walkthrough of how to use/interpret mean center
* [Quadrats](https://www.youtube.com/watch?v=AYb2IUHwvyg){target="_blank"} by BBA Science
* [Terra package tutorial](https://www.youtube.com/watch?v=LK4HeAX3VFg){target="_blank"} training by Jason Flower for a group in Brisbane, Australia