---
title: "Data Science in Geography: resource page"
format: html
editor: source
project:
  type: website
  output-dir: docs
---

There are multiple free resources online to help grow your ability to learn R for geographic analysis. Here's a few.

## Learning R

* [Hands-On Programming with R](https://rstudio-education.github.io/hopr/){target="_blank"}: This online book by Garrett Grolemund starts from the very basics and is a good primer on how to get started in R and understand things like the difference between a vector and a list or what `c(3, 5)` means.

* [R for the Rest of Us](https://rfortherestofus.com/courses/getting-started){target="_blank"} Only the introductory video lessons at this website are free, but you may find it useful as a place to start.

* [Learning Statistics with R](https://learningstatisticswithr.com/book/){target="_blank"} Good overview of getting started in R and doing statistical analysis, with an emphasis on psychology.

* [Introduction to Statistics: an integrated textbook and workbook using R](https://vectorposse.github.io/intro_stats/){target="_blank"}. Well organized and recent textbook walking through R for statistical work.

* [R for Psychological Science](https://psyr.djnavarro.net/index.html){target="_blank"} Very nice online book introducing R for analysis. It's still incomplete for more advanced methods, but good for getting started.

* [Exploratory Data Analysis with R (Peng)](https://bookdown.org/rdpeng/exdata/) Book focused specifically on exploratory analysis with `tidyverse` tools by Roger Peng, who also had [a podcast about data analysis](https://podcasts.apple.com/us/podcast/not-so-standard-deviations/id1040614570) for several years.

* [Exploratory Data Analysis in R (Gimond)](https://mgimond.github.io/ES218/) A more recent web based book on using R for EDA.

* [Teacup Giraffes and Statistics](https://tinystats.github.io/teacups-giraffes-and-statistics/index.html){target="_blank"}: Whimsically themed website with lots of interactive exercises to get you started in R, both loading data and doing statistical analysis.

* [Swirl](https://swirlstats.com/students.html){target="_blank"}: An R package that is designed to teach you R while using R.

* [Tidyverse Workflow](https://rguides.dev/tutorials/tidyverse-workflow/): From its creators. It walks through the different packages/functions within the tidyverse.

## R for research

* [The Big Book of R](https://www.bigbookofr.com/){target="_blank"}: It's a book of books! This text gives you links to a bunch of online resources for using R in a variety of academic and computational contexts.

* [R for Data Science](https://r4ds.hadley.nz/){target="_blank"}: The main text by the authors of the tidyverse on how to use R for exploratory data analysis, data wrangling, and visualization. It assumes you know your basic way around R.

* [Advanced R](https://adv-r.hadley.nz/){target="_blank"}: Hadley Wickham (the main author of the tidyverse) wrote this book to cover more advanced programming tasks in R.

* [Geocomputation with R](https://r.geocompx.org/){target="_blank"}: Online, open source book by Lovelace et al. that provides detailed examples of how R can be used for geospatial analysis.

* [Rspatial.org](https://rspatial.org/){target="_blank"}: Another site providing both an overview of spatial functions in R and examples of applications. It has the most detail on analysis of raster data. Created by Robert Hijmans, who helped author the `terra` and `raster` packages.

* [Spatial Data Science](https://r-spatial.org/book/){target="_blank"}: This book by Pebesma and Bivand, hosted on the Rspatial site, is another more technical guide to doing spatial analysis using R. Pebesma is the main author for the `sf` package.

* [Introduction to Econometrics with R](https://www.econometrics-with-r.org){target="_blank"}: This book provides a somewhat technical but useful walkthrough of everything from basic descriptive analysis through time series models and measuring causal effects.

* [Tidy Modeling with R](https://www.tmwr.org/){target="_blank"}: Max Kuhn and Julia Silghe walk through the `tidymodels` package, which provides tools for machine learning and other AI assisted modeling.

## Connecting R with other tools and data

* [ESRI's R-ArcGIS Bridge](https://www.esri.com/en-us/arcgis/products/r-arcgis-bridge/overview){target="_blank"}: This tool allows you to access, analyze, and edit feature datasets hosted on ArcGIS Online. It also allows you to use ArcGIS functions in R or to bring R functions into the ArcGIS toolbox.

* [qgisprocess](https://r-spatial.github.io/qgisprocess/){target="_blank"}: This package allows you to access the functions in the QGIS Processing Toolbox for data stored in R. Several functions in QGIS are more efficient than the equivalent version in `sf`, so this can be useful.

* [reticulate](https://rstudio.github.io/reticulate/){target="_blank"}: Developed by Posit, the reticulate package allows you to create a virtual Python environment in R and transfer objects such as data frames between R and Python. This is useful if Python offers tools that are better suited to your analysis. The [Positron](https://positron.posit.co/) application created by Posit offers a true Python environment, but lacks the ability to move objects back and forth. You instead save data in one environment and then load it in another.

## Data visualization

* [R Graphics Cookbook](https://r-graphics.org/){target="_blank"}: This book by Winston Chang walks through a variety of examples of how to specify plots using `ggplot`.

* [Data Visualization: A Practical Introduction](https://socviz.co/){target="_blank"}: Kieran Healy has lots of great material out there both on the practicals of data science but also the social science behind it. This is his book walking through data visualization in R.

## YouTube R/stats people

* [Julia Silge](https://www.youtube.com/@JuliaSilge/videos){target="_blank"}: Julia works for Posit and has been providing materials on how to use R effectively for awhile. There's a lot here on doing modeling and machine learning in R.

* [Equitable Equations on YouTube](https://www.youtube.com/playlist?list=PLKBUk9FL4nBYpUKszG4edyAiM9aeTT1yv){target="_blank"}: This account has some helpful looking videos with slow and thorough walkthroughs of working in R with the tidyverse. This link goes to his "All about R" playlist.

* [R Programming 101](https://www.youtube.com/@RProgramming101){target="_blank"}: Quick videos on getting started in R and doing statistical analysis. Plus he's British!

* [StatQuest with Josh Starmer](https://www.youtube.com/c/joshstarmer){target="_blank"}: A platform neutral page that focuses more on the concepts of various statistical approaches. Good graphics!

## Social media/communities

* [R-Bloggers](https://www.r-bloggers.com/){target="_blank"}: Feed of R related articles that may be of interest.

* [RLadies](https://rladies.org/){target="_blank"}: What it sounds like. Online community of (primarily) women with local chapters around the world.

* [TidyTuesday](https://github.com/rfordatascience/tidytuesday){target="_blank"}: Cross platform community that has a new data challenge every week.
