---
title: "Course Datasets"
format: html
editor_options: 
  chunk_output_type: console
---

This page lists datasets available in the course repository. It also links them to scripts and labs


```{r}
library(tidyverse)
library(fs)
library(here)

course_data <- read_csv("data/course_data_full.csv") %>%
  rename(file=`File name`)

#--------------------------------------------------
# List all the datasets datasets
#--------------------------------------------------
ext_cut<-c("cpg","dbf","prj","shx","tfw","xml","html")

data_files <- dir_ls(here::here("data"), recurse = TRUE, type = "file") |>
  tibble(path = _) |>
  mutate(file = path_file(path), ext = path_ext(file)) |>
  filter(!ext %in% ext_cut, file != "course_data.csv") |>
  mutate(
    URL = paste0("https://github.com/communitymaplab/geog4300_datascience/blob/main/", path),
    Link = paste0("<a href='", URL, "'>", file, "</a>")
  )

#write_csv(data_files,"data/course_data.csv")
```

Are all those data being used?

```{r}
#--------------------------------------------------
# Find scripts and labs
#--------------------------------------------------

script_files <- dir_ls(
  here(".scripts"),
  recurse = TRUE,
  regexp = "\\.(R|qmd)$",
  type = "file"
)

lab_files <- dir_ls(
  "D:/git_sync/geog4300_labs",
  recurse = TRUE,
  regexp = "\\.(R|qmd)$",
  type = "file"
)

#--------------------------------------------------
# Regular expressions for common file-reading functions
#--------------------------------------------------

patterns <- c(
  "read_csv\\(",
  "read_tsv\\(",
  "read_delim\\(",
  "read_csv2\\(",
  "read_excel\\(",
  "read_xlsx\\(",
  "st_read\\(",
  "vect\\(",
  "rast\\(",
  "readRDS\\(",
  "read_rds\\(",
  "load\\(",
  "arrow::read_parquet\\(",
  "read_parquet\\(",
  "read_feather\\(",
  "vroom\\(",
  "fread\\("
)

pattern <- paste(patterns, collapse = "|")

#--------------------------------------------------
# Extract filenames from scripts
#--------------------------------------------------

extract_files <- function(script){

  lines <- readLines(script, warn = FALSE)

  tibble(
    line = seq_along(lines),
    text = lines
  ) |>
    filter(str_detect(text, pattern)) |>
    mutate(

      filename = str_match(
        text,
        "[\"']([^\"']+\\.(csv|tsv|txt|xlsx?|gpkg|geojson|shp|rds|RDS|parquet|feather))[\"']"
      )[,2],

      script = path_file(script)
    ) |>
    filter(!is.na(filename)) |>
    select(script, line, filename)
}

script_usage <- map_dfr(script_files, extract_files) %>%
    mutate(filename=str_replace(filename,"https://github.com/jshannon75/geog4300/raw/refs/heads/master/data/",""),
            filename=str_replace(filename,"https://github.com/jshannon75/geog4300/raw/master/data/",""),
            filename=str_replace(filename,"data/",""))

lab_usage<- map_dfr(lab_files, extract_files) %>%
        mutate(filename=str_replace(filename,"https://github.com/jshannon75/geog4300/raw/refs/heads/master/data/",""),
            filename=str_replace(filename,"https://raw.githubusercontent.com/tonmcg/US_County_Level_Election_Results_08-16/master/",""),
            filename=str_replace(filename,"data/",""),
            filename=str_replace(filename,"prep_data/",""),
            filename=str_replace(filename,"setup/",""))

usage<-bind_rows(script_usage,lab_usage)
#--------------------------------------------------
# Match to datasets
#--------------------------------------------------

dataset_usage <-
  usage |>
  full_join(
    data_files |> select(file, ext, path),
    by = c("filename" = "file")
  ) |>
  separate(script,into=c("s_num","title"),sep=" ") |>
  select(-title) |>
  mutate(s_num=str_replace(s_num,"geog4300_","")) |>
  arrange(filename, s_num) |>
  group_by(filename, ext, path) |>
  summarize(
    used_in = paste(sort(unique(s_num)), collapse = ", "),
    .groups = "drop"
  )

dataset_usage
```

Remove data file listing if it's not present. Then add new files

```{r}
course_data_new<-course_data %>% 
  inner_join(data_files %>% select(file),by="file")

new<-data_files %>%
  anti_join(course_data_new,by="file") %>%
  rename(`Path in the Repo`=path,
         `File type`=ext) %>%
  select(-URL)

course_data_new1<-course_data_new %>%
  bind_rows(new) %>%
  rename(`File name`=file)

write_csv(course_data_new1,"data/course_data_full.csv")
```


Process for identifying explicitly named files

```{r}
used_files <- unique(usage$filename)

# Listed in the CSV but no longer used by any script/lab, or gone from disk
dropped <- course_data |>
  filter(!file %in% used_files | !file %in% data_files$file)

# On disk and used, but not yet in the CSV
added <- data_files |>
  filter(file %in% used_files, !file %in% course_data$file)

# Updated list: keep surviving rows (and any columns you've added by hand),
# append new files, refresh the "used_in" column
course_data_new <- course_data |>
  anti_join(dropped, by = "file") |>
  select(-any_of("used_in")) |>
  bind_rows(added) |>
  left_join(
    dataset_usage |> select(file = filename, used_in),
    by = "file"
  ) |>
  arrange(file)

# For review before anything is saved
dropped
added

# On disk, not in the CSV, and not used anywhere: candidates for deleting from the repo
data_files |>
  filter(!file %in% used_files, !file %in% course_data$file)

# Referenced in code but not found in data/ (typos, remote files, stale paths)
usage |> filter(!filename %in% data_files$file)

# Once the changes look right:
# write_csv(course_data_new, "data/course_data.csv")
```



```{r}
unused <-
  data_files |>
  anti_join(
    usage,
    by = c("file" = "filename")
  )

unused
```


```{r}
missing <-
  usage |>
  anti_join(
    data_files,
    by = c("filename" = "file")
  )

missing
```